<?php

namespace Database\Seeders;

use App\Models\Component;
use App\Models\ComponentCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ComponentSeeder extends Seeder
{
    public function run(): void
    {
        // CPU
        $cpu = ComponentCategory::where('slug', 'cpu')->first();
        $cpus = [
            // AMD AM4
            ['name' => 'AMD Ryzen 5 5600X', 'brand' => 'AMD', 'model' => 'Ryzen 5 5600X', 'base_price' => 1800000, 'tdp' => 65, 'performance_score' => 72, 'specs' => ['cores' => 6, 'threads' => 12, 'base_clock' => '3.7 GHz', 'boost_clock' => '4.6 GHz', 'socket' => 'AM4', 'cache' => '35MB', 'igpu' => false, 'cooler_included' => true], 'compatibility_tags' => ['socket:AM4']],
            ['name' => 'AMD Ryzen 5 5600G', 'brand' => 'AMD', 'model' => 'Ryzen 5 5600G', 'base_price' => 1600000, 'tdp' => 65, 'performance_score' => 68, 'specs' => ['cores' => 6, 'threads' => 12, 'base_clock' => '3.9 GHz', 'boost_clock' => '4.4 GHz', 'socket' => 'AM4', 'cache' => '19MB', 'igpu' => true, 'igpu_model' => 'Radeon Vega 7', 'cooler_included' => true], 'compatibility_tags' => ['socket:AM4', 'has:igpu']],
            ['name' => 'AMD Ryzen 7 5700X', 'brand' => 'AMD', 'model' => 'Ryzen 7 5700X', 'base_price' => 2400000, 'tdp' => 65, 'performance_score' => 78, 'specs' => ['cores' => 8, 'threads' => 16, 'base_clock' => '3.4 GHz', 'boost_clock' => '4.6 GHz', 'socket' => 'AM4', 'cache' => '36MB', 'igpu' => false, 'cooler_included' => true], 'compatibility_tags' => ['socket:AM4']],
            ['name' => 'AMD Ryzen 7 5800X3D', 'brand' => 'AMD', 'model' => 'Ryzen 7 5800X3D', 'base_price' => 3500000, 'tdp' => 105, 'performance_score' => 90, 'specs' => ['cores' => 8, 'threads' => 16, 'base_clock' => '3.4 GHz', 'boost_clock' => '4.5 GHz', 'socket' => 'AM4', 'cache' => '96MB', 'igpu' => false, 'cooler_included' => false], 'compatibility_tags' => ['socket:AM4']],
            ['name' => 'AMD Ryzen 9 5900X', 'brand' => 'AMD', 'model' => 'Ryzen 9 5900X', 'base_price' => 4200000, 'tdp' => 105, 'performance_score' => 88, 'specs' => ['cores' => 12, 'threads' => 24, 'base_clock' => '3.7 GHz', 'boost_clock' => '4.8 GHz', 'socket' => 'AM4', 'cache' => '70MB', 'igpu' => false, 'cooler_included' => false], 'compatibility_tags' => ['socket:AM4']],

            // AMD AM5
            ['name' => 'AMD Ryzen 5 7600X', 'brand' => 'AMD', 'model' => 'Ryzen 5 7600X', 'base_price' => 2800000, 'tdp' => 105, 'performance_score' => 82, 'specs' => ['cores' => 6, 'threads' => 12, 'base_clock' => '4.7 GHz', 'boost_clock' => '5.3 GHz', 'socket' => 'AM5', 'cache' => '38MB', 'igpu' => true, 'igpu_model' => 'Radeon 760M', 'cooler_included' => false], 'compatibility_tags' => ['socket:AM5', 'has:igpu']],
            ['name' => 'AMD Ryzen 5 7600', 'brand' => 'AMD', 'model' => 'Ryzen 5 7600', 'base_price' => 2500000, 'tdp' => 65, 'performance_score' => 80, 'specs' => ['cores' => 6, 'threads' => 12, 'base_clock' => '3.8 GHz', 'boost_clock' => '5.1 GHz', 'socket' => 'AM5', 'cache' => '38MB', 'igpu' => true, 'igpu_model' => 'Radeon 760M', 'cooler_included' => true], 'compatibility_tags' => ['socket:AM5', 'has:igpu']],
            ['name' => 'AMD Ryzen 7 7700X', 'brand' => 'AMD', 'model' => 'Ryzen 7 7700X', 'base_price' => 3800000, 'tdp' => 105, 'performance_score' => 87, 'specs' => ['cores' => 8, 'threads' => 16, 'base_clock' => '4.5 GHz', 'boost_clock' => '5.4 GHz', 'socket' => 'AM5', 'cache' => '40MB', 'igpu' => true, 'igpu_model' => 'Radeon 780M', 'cooler_included' => false], 'compatibility_tags' => ['socket:AM5', 'has:igpu']],
            ['name' => 'AMD Ryzen 7 7800X3D', 'brand' => 'AMD', 'model' => 'Ryzen 7 7800X3D', 'base_price' => 5500000, 'tdp' => 120, 'performance_score' => 96, 'specs' => ['cores' => 8, 'threads' => 16, 'base_clock' => '4.5 GHz', 'boost_clock' => '5.0 GHz', 'socket' => 'AM5', 'cache' => '104MB', 'igpu' => true, 'igpu_model' => 'Radeon 780M', 'cooler_included' => false], 'compatibility_tags' => ['socket:AM5', 'has:igpu']],
            ['name' => 'AMD Ryzen 9 7900X', 'brand' => 'AMD', 'model' => 'Ryzen 9 7900X', 'base_price' => 6000000, 'tdp' => 170, 'performance_score' => 92, 'specs' => ['cores' => 12, 'threads' => 24, 'base_clock' => '4.7 GHz', 'boost_clock' => '5.6 GHz', 'socket' => 'AM5', 'cache' => '76MB', 'igpu' => true, 'igpu_model' => 'Radeon 760M', 'cooler_included' => false], 'compatibility_tags' => ['socket:AM5', 'has:igpu']],
            ['name' => 'AMD Ryzen 9 7950X3D', 'brand' => 'AMD', 'model' => 'Ryzen 9 7950X3D', 'base_price' => 12000000, 'tdp' => 120, 'performance_score' => 99, 'specs' => ['cores' => 16, 'threads' => 32, 'base_clock' => '4.2 GHz', 'boost_clock' => '5.7 GHz', 'socket' => 'AM5', 'cache' => '144MB', 'igpu' => true, 'igpu_model' => 'Radeon 760M', 'cooler_included' => false], 'compatibility_tags' => ['socket:AM5', 'has:igpu']],

            // Intel LGA1700 (12th & 13th Gen)
            ['name' => 'Intel Core i3-12100F', 'brand' => 'Intel', 'model' => 'Core i3-12100F', 'base_price' => 1200000, 'tdp' => 58, 'performance_score' => 58, 'specs' => ['cores' => 4, 'threads' => 8, 'base_clock' => '3.3 GHz', 'boost_clock' => '4.3 GHz', 'socket' => 'LGA1700', 'cache' => '12MB', 'igpu' => false, 'cooler_included' => false], 'compatibility_tags' => ['socket:LGA1700']],
            ['name' => 'Intel Core i3-12100', 'brand' => 'Intel', 'model' => 'Core i3-12100', 'base_price' => 1400000, 'tdp' => 60, 'performance_score' => 58, 'specs' => ['cores' => 4, 'threads' => 8, 'base_clock' => '3.3 GHz', 'boost_clock' => '4.3 GHz', 'socket' => 'LGA1700', 'cache' => '12MB', 'igpu' => true, 'igpu_model' => 'Intel UHD 730', 'cooler_included' => true], 'compatibility_tags' => ['socket:LGA1700', 'has:igpu']],
            ['name' => 'Intel Core i5-12400F', 'brand' => 'Intel', 'model' => 'Core i5-12400F', 'base_price' => 1900000, 'tdp' => 65, 'performance_score' => 75, 'specs' => ['cores' => 6, 'threads' => 12, 'base_clock' => '2.5 GHz', 'boost_clock' => '4.4 GHz', 'socket' => 'LGA1700', 'cache' => '18MB', 'igpu' => false, 'cooler_included' => true], 'compatibility_tags' => ['socket:LGA1700']],
            ['name' => 'Intel Core i5-13400F', 'brand' => 'Intel', 'model' => 'Core i5-13400F', 'base_price' => 2600000, 'tdp' => 65, 'performance_score' => 80, 'specs' => ['cores' => 10, 'threads' => 16, 'base_clock' => '2.5 GHz', 'boost_clock' => '4.6 GHz', 'socket' => 'LGA1700', 'cache' => '20MB', 'igpu' => false, 'cooler_included' => true], 'compatibility_tags' => ['socket:LGA1700']],
            ['name' => 'Intel Core i5-13600K', 'brand' => 'Intel', 'model' => 'Core i5-13600K', 'base_price' => 3200000, 'tdp' => 125, 'performance_score' => 85, 'specs' => ['cores' => 14, 'threads' => 20, 'base_clock' => '3.5 GHz', 'boost_clock' => '5.1 GHz', 'socket' => 'LGA1700', 'cache' => '44MB', 'igpu' => true, 'igpu_model' => 'Intel UHD 770', 'cooler_included' => false], 'compatibility_tags' => ['socket:LGA1700', 'has:igpu']],
            ['name' => 'Intel Core i7-13700K', 'brand' => 'Intel', 'model' => 'Core i7-13700K', 'base_price' => 5200000, 'tdp' => 125, 'performance_score' => 91, 'specs' => ['cores' => 16, 'threads' => 24, 'base_clock' => '3.4 GHz', 'boost_clock' => '5.4 GHz', 'socket' => 'LGA1700', 'cache' => '54MB', 'igpu' => true, 'igpu_model' => 'Intel UHD 770', 'cooler_included' => false], 'compatibility_tags' => ['socket:LGA1700', 'has:igpu']],
            ['name' => 'Intel Core i9-13900K', 'brand' => 'Intel', 'model' => 'Core i9-13900K', 'base_price' => 8500000, 'tdp' => 125, 'performance_score' => 97, 'specs' => ['cores' => 24, 'threads' => 32, 'base_clock' => '3.0 GHz', 'boost_clock' => '5.8 GHz', 'socket' => 'LGA1700', 'cache' => '68MB', 'igpu' => true, 'igpu_model' => 'Intel UHD 770', 'cooler_included' => false], 'compatibility_tags' => ['socket:LGA1700', 'has:igpu']],

            // Intel LGA1851 (14th Gen / Arrow Lake)
            ['name' => 'Intel Core Ultra 5 245K', 'brand' => 'Intel', 'model' => 'Core Ultra 5 245K', 'base_price' => 4500000, 'tdp' => 125, 'performance_score' => 84, 'specs' => ['cores' => 14, 'threads' => 14, 'base_clock' => '3.6 GHz', 'boost_clock' => '5.2 GHz', 'socket' => 'LGA1851', 'cache' => '24MB', 'igpu' => true, 'igpu_model' => 'Intel Arc 140V', 'cooler_included' => false], 'compatibility_tags' => ['socket:LGA1851', 'has:igpu']],
            ['name' => 'Intel Core Ultra 7 265K', 'brand' => 'Intel', 'model' => 'Core Ultra 7 265K', 'base_price' => 6000000, 'tdp' => 125, 'performance_score' => 90, 'specs' => ['cores' => 20, 'threads' => 20, 'base_clock' => '3.9 GHz', 'boost_clock' => '5.5 GHz', 'socket' => 'LGA1851', 'cache' => '30MB', 'igpu' => true, 'igpu_model' => 'Intel Arc 140V', 'cooler_included' => false], 'compatibility_tags' => ['socket:LGA1851', 'has:igpu']],
            ['name' => 'Intel Core Ultra 9 285K', 'brand' => 'Intel', 'model' => 'Core Ultra 9 285K', 'base_price' => 9000000, 'tdp' => 125, 'performance_score' => 95, 'specs' => ['cores' => 24, 'threads' => 24, 'base_clock' => '3.7 GHz', 'boost_clock' => '5.7 GHz', 'socket' => 'LGA1851', 'cache' => '36MB', 'igpu' => true, 'igpu_model' => 'Intel Arc 140V', 'cooler_included' => false], 'compatibility_tags' => ['socket:LGA1851', 'has:igpu']],
        ];
        foreach ($cpus as $item) {
            Component::create(['id' => Str::uuid(), 'category_id' => $cpu->id, ...$item]);
        }

        // GPU
        $gpu = ComponentCategory::where('slug', 'gpu')->first();
        $gpus = [
            // NVIDIA RTX 40 Series
            ['name' => 'NVIDIA RTX 4060', 'brand' => 'NVIDIA', 'model' => 'RTX 4060', 'base_price' => 4500000, 'tdp' => 115, 'performance_score' => 75, 'specs' => ['vram' => '8GB GDDR6', 'bus_width' => '128-bit', 'boost_clock' => '2460 MHz', 'pcie' => 'PCIe 4.0 x8', 'power_connector' => '1x 16-pin', 'recommended_psu' => 550], 'compatibility_tags' => ['pcie:4.0', 'psu_min:550']],
            ['name' => 'NVIDIA RTX 4060 Ti', 'brand' => 'NVIDIA', 'model' => 'RTX 4060 Ti', 'base_price' => 6000000, 'tdp' => 165, 'performance_score' => 82, 'specs' => ['vram' => '8GB GDDR6', 'bus_width' => '128-bit', 'boost_clock' => '2535 MHz', 'pcie' => 'PCIe 4.0 x8', 'power_connector' => '1x 16-pin', 'recommended_psu' => 650], 'compatibility_tags' => ['pcie:4.0', 'psu_min:550']],
            ['name' => 'NVIDIA RTX 4070', 'brand' => 'NVIDIA', 'model' => 'RTX 4070', 'base_price' => 7500000, 'tdp' => 200, 'performance_score' => 88, 'specs' => ['vram' => '12GB GDDR6X', 'bus_width' => '192-bit', 'boost_clock' => '2475 MHz', 'pcie' => 'PCIe 4.0 x16', 'power_connector' => '1x 16-pin', 'recommended_psu' => 650], 'compatibility_tags' => ['pcie:4.0', 'psu_min:650']],
            ['name' => 'NVIDIA RTX 4070 Super', 'brand' => 'NVIDIA', 'model' => 'RTX 4070 Super', 'base_price' => 9000000, 'tdp' => 220, 'performance_score' => 91, 'specs' => ['vram' => '12GB GDDR6X', 'bus_width' => '192-bit', 'boost_clock' => '2520 MHz', 'pcie' => 'PCIe 4.0 x16', 'power_connector' => '1x 16-pin', 'recommended_psu' => 700], 'compatibility_tags' => ['pcie:4.0', 'psu_min:650']],
            ['name' => 'NVIDIA RTX 4070 Ti Super', 'brand' => 'NVIDIA', 'model' => 'RTX 4070 Ti Super', 'base_price' => 12000000, 'tdp' => 285, 'performance_score' => 94, 'specs' => ['vram' => '16GB GDDR6X', 'bus_width' => '256-bit', 'boost_clock' => '2610 MHz', 'pcie' => 'PCIe 4.0 x16', 'power_connector' => '2x 8-pin or 1x 16-pin', 'recommended_psu' => 800], 'compatibility_tags' => ['pcie:4.0', 'psu_min:750']],
            ['name' => 'NVIDIA RTX 4080 Super', 'brand' => 'NVIDIA', 'model' => 'RTX 4080 Super', 'base_price' => 17000000, 'tdp' => 320, 'performance_score' => 96, 'specs' => ['vram' => '16GB GDDR6X', 'bus_width' => '256-bit', 'boost_clock' => '2550 MHz', 'pcie' => 'PCIe 4.0 x16', 'power_connector' => '3x 8-pin or 1x 16-pin', 'recommended_psu' => 850], 'compatibility_tags' => ['pcie:4.0', 'psu_min:850']],
            ['name' => 'NVIDIA RTX 4090', 'brand' => 'NVIDIA', 'model' => 'RTX 4090', 'base_price' => 28000000, 'tdp' => 450, 'performance_score' => 100, 'specs' => ['vram' => '24GB GDDR6X', 'bus_width' => '384-bit', 'boost_clock' => '2520 MHz', 'pcie' => 'PCIe 4.0 x16', 'power_connector' => '3x 8-pin or 1x 16-pin', 'recommended_psu' => 850], 'compatibility_tags' => ['pcie:4.0', 'psu_min:850']],

            // AMD RX 7000 Series
            ['name' => 'AMD RX 7600', 'brand' => 'AMD', 'model' => 'RX 7600', 'base_price' => 3800000, 'tdp' => 165, 'performance_score' => 70, 'specs' => ['vram' => '8GB GDDR6', 'bus_width' => '128-bit', 'boost_clock' => '2655 MHz', 'pcie' => 'PCIe 4.0 x8', 'power_connector' => '1x 8-pin', 'recommended_psu' => 550], 'compatibility_tags' => ['pcie:4.0', 'psu_min:550']],
            ['name' => 'AMD RX 7700 XT', 'brand' => 'AMD', 'model' => 'RX 7700 XT', 'base_price' => 5500000, 'tdp' => 245, 'performance_score' => 81, 'specs' => ['vram' => '12GB GDDR6', 'bus_width' => '192-bit', 'boost_clock' => '2544 MHz', 'pcie' => 'PCIe 4.0 x8', 'power_connector' => '2x 8-pin', 'recommended_psu' => 700], 'compatibility_tags' => ['pcie:4.0', 'psu_min:650']],
            ['name' => 'AMD RX 7800 XT', 'brand' => 'AMD', 'model' => 'RX 7800 XT', 'base_price' => 7000000, 'tdp' => 263, 'performance_score' => 86, 'specs' => ['vram' => '16GB GDDR6', 'bus_width' => '256-bit', 'boost_clock' => '2430 MHz', 'pcie' => 'PCIe 4.0 x8', 'power_connector' => '2x 8-pin', 'recommended_psu' => 700], 'compatibility_tags' => ['pcie:4.0', 'psu_min:700']],
            ['name' => 'AMD RX 7900 GRE', 'brand' => 'AMD', 'model' => 'RX 7900 GRE', 'base_price' => 9500000, 'tdp' => 260, 'performance_score' => 90, 'specs' => ['vram' => '16GB GDDR6', 'bus_width' => '256-bit', 'boost_clock' => '2245 MHz', 'pcie' => 'PCIe 4.0 x16', 'power_connector' => '2x 8-pin', 'recommended_psu' => 750], 'compatibility_tags' => ['pcie:4.0', 'psu_min:750']],
            ['name' => 'AMD RX 7900 XT', 'brand' => 'AMD', 'model' => 'RX 7900 XT', 'base_price' => 13000000, 'tdp' => 315, 'performance_score' => 93, 'specs' => ['vram' => '20GB GDDR6', 'bus_width' => '320-bit', 'boost_clock' => '2394 MHz', 'pcie' => 'PCIe 4.0 x16', 'power_connector' => '2x 8-pin', 'recommended_psu' => 800], 'compatibility_tags' => ['pcie:4.0', 'psu_min:800']],
            ['name' => 'AMD RX 7900 XTX', 'brand' => 'AMD', 'model' => 'RX 7900 XTX', 'base_price' => 16000000, 'tdp' => 355, 'performance_score' => 97, 'specs' => ['vram' => '24GB GDDR6', 'bus_width' => '384-bit', 'boost_clock' => '2499 MHz', 'pcie' => 'PCIe 4.0 x16', 'power_connector' => '2x 8-pin', 'recommended_psu' => 850], 'compatibility_tags' => ['pcie:4.0', 'psu_min:850']],

            // Budget / entry level
            ['name' => 'NVIDIA GTX 1650', 'brand' => 'NVIDIA', 'model' => 'GTX 1650', 'base_price' => 1800000, 'tdp' => 75, 'performance_score' => 40, 'specs' => ['vram' => '4GB GDDR6', 'bus_width' => '128-bit', 'boost_clock' => '1665 MHz', 'pcie' => 'PCIe 3.0 x16', 'power_connector' => 'None (slot powered)', 'recommended_psu' => 300], 'compatibility_tags' => ['pcie:3.0', 'psu_min:300']],
            ['name' => 'NVIDIA RTX 3060', 'brand' => 'NVIDIA', 'model' => 'RTX 3060', 'base_price' => 3500000, 'tdp' => 170, 'performance_score' => 68, 'specs' => ['vram' => '12GB GDDR6', 'bus_width' => '192-bit', 'boost_clock' => '1777 MHz', 'pcie' => 'PCIe 4.0 x16', 'power_connector' => '1x 12-pin', 'recommended_psu' => 550], 'compatibility_tags' => ['pcie:4.0', 'psu_min:550']],
        ];
        foreach ($gpus as $item) {
            Component::create(['id' => Str::uuid(), 'category_id' => $gpu->id, ...$item]);
        }

        // MOTHERBOARD
        $mobo = ComponentCategory::where('slug', 'motherboard')->first();
        $mobos = [
            // AM4 Boards
            ['name' => 'ASUS ROG Strix B550-F Gaming', 'brand' => 'ASUS', 'model' => 'ROG Strix B550-F', 'base_price' => 2200000, 'tdp' => null, 'performance_score' => 75, 'specs' => ['socket' => 'AM4', 'chipset' => 'B550', 'form_factor' => 'ATX', 'ram_slots' => 4, 'max_ram' => '128GB', 'ram_type' => 'DDR4', 'pcie_slots' => 2, 'nvme_slots' => 2, 'usb_c' => true], 'compatibility_tags' => ['socket:AM4', 'ram:DDR4', 'form_factor:ATX']],
            ['name' => 'MSI B450M Pro-VDH Max', 'brand' => 'MSI', 'model' => 'B450M Pro-VDH Max', 'base_price' => 1100000, 'tdp' => null, 'performance_score' => 55, 'specs' => ['socket' => 'AM4', 'chipset' => 'B450', 'form_factor' => 'mATX', 'ram_slots' => 4, 'max_ram' => '64GB', 'ram_type' => 'DDR4', 'pcie_slots' => 1, 'nvme_slots' => 1, 'usb_c' => false], 'compatibility_tags' => ['socket:AM4', 'ram:DDR4', 'form_factor:mATX']],
            ['name' => 'Gigabyte B550 AORUS Elite V2', 'brand' => 'Gigabyte', 'model' => 'B550 AORUS Elite V2', 'base_price' => 2000000, 'tdp' => null, 'performance_score' => 73, 'specs' => ['socket' => 'AM4', 'chipset' => 'B550', 'form_factor' => 'ATX', 'ram_slots' => 4, 'max_ram' => '128GB', 'ram_type' => 'DDR4', 'pcie_slots' => 2, 'nvme_slots' => 2, 'usb_c' => true], 'compatibility_tags' => ['socket:AM4', 'ram:DDR4', 'form_factor:ATX']],
            ['name' => 'ASRock X570 Phantom Gaming 4', 'brand' => 'ASRock', 'model' => 'X570 Phantom Gaming 4', 'base_price' => 2400000, 'tdp' => null, 'performance_score' => 78, 'specs' => ['socket' => 'AM4', 'chipset' => 'X570', 'form_factor' => 'ATX', 'ram_slots' => 4, 'max_ram' => '128GB', 'ram_type' => 'DDR4', 'pcie_slots' => 3, 'nvme_slots' => 2, 'usb_c' => true], 'compatibility_tags' => ['socket:AM4', 'ram:DDR4', 'form_factor:ATX']],

            // AM5 Boards
            ['name' => 'Gigabyte B650 AORUS Elite AX', 'brand' => 'Gigabyte', 'model' => 'B650 AORUS Elite AX', 'base_price' => 3100000, 'tdp' => null, 'performance_score' => 80, 'specs' => ['socket' => 'AM5', 'chipset' => 'B650', 'form_factor' => 'ATX', 'ram_slots' => 4, 'max_ram' => '192GB', 'ram_type' => 'DDR5', 'pcie_slots' => 2, 'nvme_slots' => 2, 'usb_c' => true], 'compatibility_tags' => ['socket:AM5', 'ram:DDR5', 'form_factor:ATX']],
            ['name' => 'MSI MAG B650M Mortar WiFi', 'brand' => 'MSI', 'model' => 'MAG B650M Mortar WiFi', 'base_price' => 2800000, 'tdp' => null, 'performance_score' => 77, 'specs' => ['socket' => 'AM5', 'chipset' => 'B650', 'form_factor' => 'mATX', 'ram_slots' => 4, 'max_ram' => '192GB', 'ram_type' => 'DDR5', 'pcie_slots' => 1, 'nvme_slots' => 2, 'usb_c' => true], 'compatibility_tags' => ['socket:AM5', 'ram:DDR5', 'form_factor:mATX']],
            ['name' => 'ASUS TUF Gaming X670E-Plus WiFi', 'brand' => 'ASUS', 'model' => 'TUF Gaming X670E-Plus WiFi', 'base_price' => 4500000, 'tdp' => null, 'performance_score' => 85, 'specs' => ['socket' => 'AM5', 'chipset' => 'X670E', 'form_factor' => 'ATX', 'ram_slots' => 4, 'max_ram' => '192GB', 'ram_type' => 'DDR5', 'pcie_slots' => 3, 'nvme_slots' => 4, 'usb_c' => true], 'compatibility_tags' => ['socket:AM5', 'ram:DDR5', 'form_factor:ATX']],
            ['name' => 'ASRock B650E PG Riptide WiFi', 'brand' => 'ASRock', 'model' => 'B650E PG Riptide WiFi', 'base_price' => 3500000, 'tdp' => null, 'performance_score' => 82, 'specs' => ['socket' => 'AM5', 'chipset' => 'B650E', 'form_factor' => 'ATX', 'ram_slots' => 4, 'max_ram' => '192GB', 'ram_type' => 'DDR5', 'pcie_slots' => 2, 'nvme_slots' => 3, 'usb_c' => true], 'compatibility_tags' => ['socket:AM5', 'ram:DDR5', 'form_factor:ATX']],

            // Intel LGA1700 Boards
            ['name' => 'MSI PRO B760M-A DDR4', 'brand' => 'MSI', 'model' => 'PRO B760M-A DDR4', 'base_price' => 1600000, 'tdp' => null, 'performance_score' => 65, 'specs' => ['socket' => 'LGA1700', 'chipset' => 'B760', 'form_factor' => 'mATX', 'ram_slots' => 2, 'max_ram' => '64GB', 'ram_type' => 'DDR4', 'pcie_slots' => 1, 'nvme_slots' => 1, 'usb_c' => false], 'compatibility_tags' => ['socket:LGA1700', 'ram:DDR4', 'form_factor:mATX']],
            ['name' => 'MSI PRO B760M-A DDR5', 'brand' => 'MSI', 'model' => 'PRO B760M-A DDR5', 'base_price' => 1800000, 'tdp' => null, 'performance_score' => 67, 'specs' => ['socket' => 'LGA1700', 'chipset' => 'B760', 'form_factor' => 'mATX', 'ram_slots' => 2, 'max_ram' => '64GB', 'ram_type' => 'DDR5', 'pcie_slots' => 1, 'nvme_slots' => 1, 'usb_c' => false], 'compatibility_tags' => ['socket:LGA1700', 'ram:DDR5', 'form_factor:mATX']],
            ['name' => 'Gigabyte B760 AORUS Elite AX DDR4', 'brand' => 'Gigabyte', 'model' => 'B760 AORUS Elite AX DDR4', 'base_price' => 2200000, 'tdp' => null, 'performance_score' => 72, 'specs' => ['socket' => 'LGA1700', 'chipset' => 'B760', 'form_factor' => 'ATX', 'ram_slots' => 4, 'max_ram' => '128GB', 'ram_type' => 'DDR4', 'pcie_slots' => 2, 'nvme_slots' => 2, 'usb_c' => true], 'compatibility_tags' => ['socket:LGA1700', 'ram:DDR4', 'form_factor:ATX']],
            ['name' => 'ASUS ROG Strix Z790-E Gaming WiFi', 'brand' => 'ASUS', 'model' => 'ROG Strix Z790-E Gaming WiFi', 'base_price' => 7000000, 'tdp' => null, 'performance_score' => 92, 'specs' => ['socket' => 'LGA1700', 'chipset' => 'Z790', 'form_factor' => 'ATX', 'ram_slots' => 4, 'max_ram' => '192GB', 'ram_type' => 'DDR5', 'pcie_slots' => 4, 'nvme_slots' => 5, 'usb_c' => true], 'compatibility_tags' => ['socket:LGA1700', 'ram:DDR5', 'form_factor:ATX']],
            ['name' => 'MSI MAG Z790 Tomahawk WiFi DDR4', 'brand' => 'MSI', 'model' => 'MAG Z790 Tomahawk WiFi DDR4', 'base_price' => 3500000, 'tdp' => null, 'performance_score' => 83, 'specs' => ['socket' => 'LGA1700', 'chipset' => 'Z790', 'form_factor' => 'ATX', 'ram_slots' => 4, 'max_ram' => '128GB', 'ram_type' => 'DDR4', 'pcie_slots' => 3, 'nvme_slots' => 4, 'usb_c' => true], 'compatibility_tags' => ['socket:LGA1700', 'ram:DDR4', 'form_factor:ATX']],
            ['name' => 'ASRock B660M Pro RS DDR4', 'brand' => 'ASRock', 'model' => 'B660M Pro RS DDR4', 'base_price' => 1400000, 'tdp' => null, 'performance_score' => 62, 'specs' => ['socket' => 'LGA1700', 'chipset' => 'B660', 'form_factor' => 'mATX', 'ram_slots' => 4, 'max_ram' => '128GB', 'ram_type' => 'DDR4', 'pcie_slots' => 2, 'nvme_slots' => 2, 'usb_c' => false], 'compatibility_tags' => ['socket:LGA1700', 'ram:DDR4', 'form_factor:mATX']],

            // Intel LGA1851 Boards (Z890)
            ['name' => 'ASUS TUF Gaming Z890-Plus WiFi', 'brand' => 'ASUS', 'model' => 'TUF Gaming Z890-Plus WiFi', 'base_price' => 5500000, 'tdp' => null, 'performance_score' => 87, 'specs' => ['socket' => 'LGA1851', 'chipset' => 'Z890', 'form_factor' => 'ATX', 'ram_slots' => 4, 'max_ram' => '256GB', 'ram_type' => 'DDR5', 'pcie_slots' => 3, 'nvme_slots' => 4, 'usb_c' => true], 'compatibility_tags' => ['socket:LGA1851', 'ram:DDR5', 'form_factor:ATX']],
            ['name' => 'MSI MAG Z890 Tomahawk WiFi', 'brand' => 'MSI', 'model' => 'MAG Z890 Tomahawk WiFi', 'base_price' => 4800000, 'tdp' => null, 'performance_score' => 85, 'specs' => ['socket' => 'LGA1851', 'chipset' => 'Z890', 'form_factor' => 'ATX', 'ram_slots' => 4, 'max_ram' => '256GB', 'ram_type' => 'DDR5', 'pcie_slots' => 3, 'nvme_slots' => 4, 'usb_c' => true], 'compatibility_tags' => ['socket:LGA1851', 'ram:DDR5', 'form_factor:ATX']],
        ];
        foreach ($mobos as $item) {
            Component::create(['id' => Str::uuid(), 'category_id' => $mobo->id, ...$item]);
        }

        // RAM
        $ram = ComponentCategory::where('slug', 'ram')->first();
        $rams = [
            // DDR4
            ['name' => 'Corsair Vengeance LPX 16GB DDR4 3200MHz', 'brand' => 'Corsair', 'model' => 'Vengeance LPX DDR4 3200', 'base_price' => 650000, 'tdp' => 5, 'performance_score' => 65, 'specs' => ['capacity' => '16GB', 'type' => 'DDR4', 'speed' => '3200MHz', 'modules' => '2x8GB', 'latency' => 'CL16', 'voltage' => '1.35V'], 'compatibility_tags' => ['ram:DDR4']],
            ['name' => 'Corsair Vengeance LPX 32GB DDR4 3200MHz', 'brand' => 'Corsair', 'model' => 'Vengeance LPX DDR4 3200 32GB', 'base_price' => 1200000, 'tdp' => 5, 'performance_score' => 66, 'specs' => ['capacity' => '32GB', 'type' => 'DDR4', 'speed' => '3200MHz', 'modules' => '2x16GB', 'latency' => 'CL16', 'voltage' => '1.35V'], 'compatibility_tags' => ['ram:DDR4']],
            ['name' => 'G.Skill Ripjaws V 16GB DDR4 3600MHz', 'brand' => 'G.Skill', 'model' => 'Ripjaws V DDR4 3600', 'base_price' => 750000, 'tdp' => 5, 'performance_score' => 70, 'specs' => ['capacity' => '16GB', 'type' => 'DDR4', 'speed' => '3600MHz', 'modules' => '2x8GB', 'latency' => 'CL18', 'voltage' => '1.35V'], 'compatibility_tags' => ['ram:DDR4']],
            ['name' => 'G.Skill Ripjaws V 32GB DDR4 3600MHz', 'brand' => 'G.Skill', 'model' => 'Ripjaws V DDR4 3600 32GB', 'base_price' => 1400000, 'tdp' => 5, 'performance_score' => 71, 'specs' => ['capacity' => '32GB', 'type' => 'DDR4', 'speed' => '3600MHz', 'modules' => '2x16GB', 'latency' => 'CL18', 'voltage' => '1.35V'], 'compatibility_tags' => ['ram:DDR4']],
            ['name' => 'Kingston Fury Beast 16GB DDR4 3200MHz', 'brand' => 'Kingston', 'model' => 'Fury Beast DDR4 3200', 'base_price' => 600000, 'tdp' => 5, 'performance_score' => 64, 'specs' => ['capacity' => '16GB', 'type' => 'DDR4', 'speed' => '3200MHz', 'modules' => '2x8GB', 'latency' => 'CL16', 'voltage' => '1.35V'], 'compatibility_tags' => ['ram:DDR4']],
            ['name' => 'Team T-Force Vulcan Z 16GB DDR4 3200MHz', 'brand' => 'Team', 'model' => 'T-Force Vulcan Z DDR4 3200', 'base_price' => 580000, 'tdp' => 5, 'performance_score' => 63, 'specs' => ['capacity' => '16GB', 'type' => 'DDR4', 'speed' => '3200MHz', 'modules' => '2x8GB', 'latency' => 'CL16', 'voltage' => '1.35V'], 'compatibility_tags' => ['ram:DDR4']],

            // DDR5
            ['name' => 'G.Skill Trident Z5 32GB DDR5 6000MHz', 'brand' => 'G.Skill', 'model' => 'Trident Z5 DDR5 6000', 'base_price' => 1800000, 'tdp' => 8, 'performance_score' => 85, 'specs' => ['capacity' => '32GB', 'type' => 'DDR5', 'speed' => '6000MHz', 'modules' => '2x16GB', 'latency' => 'CL30', 'voltage' => '1.35V'], 'compatibility_tags' => ['ram:DDR5']],
            ['name' => 'G.Skill Trident Z5 64GB DDR5 6000MHz', 'brand' => 'G.Skill', 'model' => 'Trident Z5 DDR5 6000 64GB', 'base_price' => 3400000, 'tdp' => 8, 'performance_score' => 86, 'specs' => ['capacity' => '64GB', 'type' => 'DDR5', 'speed' => '6000MHz', 'modules' => '2x32GB', 'latency' => 'CL30', 'voltage' => '1.35V'], 'compatibility_tags' => ['ram:DDR5']],
            ['name' => 'Corsair Dominator Titanium 32GB DDR5 6000MHz', 'brand' => 'Corsair', 'model' => 'Dominator Titanium DDR5 6000', 'base_price' => 2200000, 'tdp' => 8, 'performance_score' => 87, 'specs' => ['capacity' => '32GB', 'type' => 'DDR5', 'speed' => '6000MHz', 'modules' => '2x16GB', 'latency' => 'CL30', 'voltage' => '1.40V'], 'compatibility_tags' => ['ram:DDR5']],
            ['name' => 'Kingston Fury Beast 32GB DDR5 5200MHz', 'brand' => 'Kingston', 'model' => 'Fury Beast DDR5 5200', 'base_price' => 1500000, 'tdp' => 7, 'performance_score' => 80, 'specs' => ['capacity' => '32GB', 'type' => 'DDR5', 'speed' => '5200MHz', 'modules' => '2x16GB', 'latency' => 'CL40', 'voltage' => '1.25V'], 'compatibility_tags' => ['ram:DDR5']],
            ['name' => 'Crucial Pro 32GB DDR5 5600MHz', 'brand' => 'Crucial', 'model' => 'Pro DDR5 5600', 'base_price' => 1400000, 'tdp' => 7, 'performance_score' => 78, 'specs' => ['capacity' => '32GB', 'type' => 'DDR5', 'speed' => '5600MHz', 'modules' => '2x16GB', 'latency' => 'CL46', 'voltage' => '1.1V'], 'compatibility_tags' => ['ram:DDR5']],
            ['name' => 'Teamgroup T-Force Delta 32GB DDR5 6400MHz', 'brand' => 'Teamgroup', 'model' => 'T-Force Delta DDR5 6400', 'base_price' => 1900000, 'tdp' => 8, 'performance_score' => 83, 'specs' => ['capacity' => '32GB', 'type' => 'DDR5', 'speed' => '6400MHz', 'modules' => '2x16GB', 'latency' => 'CL32', 'voltage' => '1.40V'], 'compatibility_tags' => ['ram:DDR5']],
        ];
        foreach ($rams as $item) {
            Component::create(['id' => Str::uuid(), 'category_id' => $ram->id, ...$item]);
        }

        // PSU
        $psu = ComponentCategory::where('slug', 'psu')->first();
        $psus = [
            ['name' => 'Corsair CV450 450W 80+ Bronze', 'brand' => 'Corsair', 'model' => 'CV450', 'base_price' => 500000, 'tdp' => null, 'performance_score' => 50, 'specs' => ['wattage' => 450, 'efficiency' => '80+ Bronze', 'modular' => 'Non-modular', 'form_factor' => 'ATX', 'atx_12v' => false], 'compatibility_tags' => ['psu_watt:450', 'form_factor:ATX']],
            ['name' => 'Corsair CV550 550W 80+ Bronze', 'brand' => 'Corsair', 'model' => 'CV550', 'base_price' => 650000, 'tdp' => null, 'performance_score' => 60, 'specs' => ['wattage' => 550, 'efficiency' => '80+ Bronze', 'modular' => 'Non-modular', 'form_factor' => 'ATX', 'atx_12v' => false], 'compatibility_tags' => ['psu_watt:550', 'form_factor:ATX']],
            ['name' => 'Seasonic Focus GX-650 650W 80+ Gold', 'brand' => 'Seasonic', 'model' => 'Focus GX-650', 'base_price' => 1100000, 'tdp' => null, 'performance_score' => 80, 'specs' => ['wattage' => 650, 'efficiency' => '80+ Gold', 'modular' => 'Full-modular', 'form_factor' => 'ATX', 'atx_12v' => false], 'compatibility_tags' => ['psu_watt:650', 'form_factor:ATX']],
            ['name' => 'Seasonic Focus GX-750 750W 80+ Gold', 'brand' => 'Seasonic', 'model' => 'Focus GX-750', 'base_price' => 1350000, 'tdp' => null, 'performance_score' => 85, 'specs' => ['wattage' => 750, 'efficiency' => '80+ Gold', 'modular' => 'Full-modular', 'form_factor' => 'ATX', 'atx_12v' => false], 'compatibility_tags' => ['psu_watt:750', 'form_factor:ATX']],
            ['name' => 'Seasonic Focus GX-850 850W 80+ Gold', 'brand' => 'Seasonic', 'model' => 'Focus GX-850', 'base_price' => 1600000, 'tdp' => null, 'performance_score' => 87, 'specs' => ['wattage' => 850, 'efficiency' => '80+ Gold', 'modular' => 'Full-modular', 'form_factor' => 'ATX', 'atx_12v' => false], 'compatibility_tags' => ['psu_watt:850', 'form_factor:ATX']],
            ['name' => 'Corsair RM1000x 1000W 80+ Gold', 'brand' => 'Corsair', 'model' => 'RM1000x', 'base_price' => 2200000, 'tdp' => null, 'performance_score' => 90, 'specs' => ['wattage' => 1000, 'efficiency' => '80+ Gold', 'modular' => 'Full-modular', 'form_factor' => 'ATX', 'atx_12v' => true], 'compatibility_tags' => ['psu_watt:1000', 'form_factor:ATX']],
            ['name' => 'EVGA SuperNOVA 1300 G+ 1300W 80+ Gold', 'brand' => 'EVGA', 'model' => 'SuperNOVA 1300 G+', 'base_price' => 3200000, 'tdp' => null, 'performance_score' => 92, 'specs' => ['wattage' => 1300, 'efficiency' => '80+ Gold', 'modular' => 'Full-modular', 'form_factor' => 'ATX', 'atx_12v' => true], 'compatibility_tags' => ['psu_watt:1300', 'form_factor:ATX']],
            ['name' => 'be quiet! Pure Power 12 M 650W 80+ Gold', 'brand' => 'be quiet!', 'model' => 'Pure Power 12 M 650W', 'base_price' => 1050000, 'tdp' => null, 'performance_score' => 78, 'specs' => ['wattage' => 650, 'efficiency' => '80+ Gold', 'modular' => 'Semi-modular', 'form_factor' => 'ATX', 'atx_12v' => false], 'compatibility_tags' => ['psu_watt:650', 'form_factor:ATX']],
            ['name' => 'Cooler Master MWE Gold 750W V2', 'brand' => 'Cooler Master', 'model' => 'MWE Gold 750 V2', 'base_price' => 1000000, 'tdp' => null, 'performance_score' => 76, 'specs' => ['wattage' => 750, 'efficiency' => '80+ Gold', 'modular' => 'Non-modular', 'form_factor' => 'ATX', 'atx_12v' => false], 'compatibility_tags' => ['psu_watt:750', 'form_factor:ATX']],
            ['name' => 'Thermaltake Toughpower GF3 1000W 80+ Gold ATX 3.0', 'brand' => 'Thermaltake', 'model' => 'Toughpower GF3 1000W', 'base_price' => 2000000, 'tdp' => null, 'performance_score' => 88, 'specs' => ['wattage' => 1000, 'efficiency' => '80+ Gold', 'modular' => 'Full-modular', 'form_factor' => 'ATX', 'atx_12v' => true], 'compatibility_tags' => ['psu_watt:1000', 'form_factor:ATX']],
        ];
        foreach ($psus as $item) {
            Component::create(['id' => Str::uuid(), 'category_id' => $psu->id, ...$item]);
        }

        // STORAGE
        $storage = ComponentCategory::where('slug', 'storage')->first();
        $storages = [
            // NVMe Gen 3
            ['name' => 'Samsung 970 EVO Plus 1TB NVMe', 'brand' => 'Samsung', 'model' => '970 EVO Plus 1TB', 'base_price' => 950000, 'tdp' => 6, 'performance_score' => 82, 'specs' => ['capacity' => '1TB', 'type' => 'NVMe SSD', 'interface' => 'M.2 PCIe 3.0 x4', 'read_speed' => '3500 MB/s', 'write_speed' => '3300 MB/s', 'form_factor' => 'M.2 2280'], 'compatibility_tags' => ['storage:nvme', 'storage:m2', 'pcie_gen:3']],
            ['name' => 'WD Blue SN570 1TB NVMe', 'brand' => 'Western Digital', 'model' => 'Blue SN570 1TB', 'base_price' => 700000, 'tdp' => 4, 'performance_score' => 75, 'specs' => ['capacity' => '1TB', 'type' => 'NVMe SSD', 'interface' => 'M.2 PCIe 3.0 x4', 'read_speed' => '3500 MB/s', 'write_speed' => '3000 MB/s', 'form_factor' => 'M.2 2280'], 'compatibility_tags' => ['storage:nvme', 'storage:m2', 'pcie_gen:3']],

            // NVMe Gen 4
            ['name' => 'WD Blue SN580 1TB NVMe Gen4', 'brand' => 'Western Digital', 'model' => 'Blue SN580 1TB', 'base_price' => 750000, 'tdp' => 5, 'performance_score' => 80, 'specs' => ['capacity' => '1TB', 'type' => 'NVMe SSD', 'interface' => 'M.2 PCIe 4.0 x4', 'read_speed' => '4150 MB/s', 'write_speed' => '4150 MB/s', 'form_factor' => 'M.2 2280'], 'compatibility_tags' => ['storage:nvme', 'storage:m2', 'pcie_gen:4']],
            ['name' => 'Samsung 980 Pro 1TB NVMe Gen4', 'brand' => 'Samsung', 'model' => '980 Pro 1TB', 'base_price' => 1100000, 'tdp' => 7, 'performance_score' => 88, 'specs' => ['capacity' => '1TB', 'type' => 'NVMe SSD', 'interface' => 'M.2 PCIe 4.0 x4', 'read_speed' => '7000 MB/s', 'write_speed' => '5100 MB/s', 'form_factor' => 'M.2 2280'], 'compatibility_tags' => ['storage:nvme', 'storage:m2', 'pcie_gen:4']],
            ['name' => 'Samsung 990 Pro 2TB NVMe Gen4', 'brand' => 'Samsung', 'model' => '990 Pro 2TB', 'base_price' => 2200000, 'tdp' => 7, 'performance_score' => 92, 'specs' => ['capacity' => '2TB', 'type' => 'NVMe SSD', 'interface' => 'M.2 PCIe 4.0 x4', 'read_speed' => '7450 MB/s', 'write_speed' => '6900 MB/s', 'form_factor' => 'M.2 2280'], 'compatibility_tags' => ['storage:nvme', 'storage:m2', 'pcie_gen:4']],
            ['name' => 'Seagate FireCuda 530 1TB NVMe Gen4', 'brand' => 'Seagate', 'model' => 'FireCuda 530 1TB', 'base_price' => 1300000, 'tdp' => 9, 'performance_score' => 90, 'specs' => ['capacity' => '1TB', 'type' => 'NVMe SSD', 'interface' => 'M.2 PCIe 4.0 x4', 'read_speed' => '7300 MB/s', 'write_speed' => '6000 MB/s', 'form_factor' => 'M.2 2280'], 'compatibility_tags' => ['storage:nvme', 'storage:m2', 'pcie_gen:4']],
            ['name' => 'Kingston Fury Renegade 1TB NVMe Gen4', 'brand' => 'Kingston', 'model' => 'Fury Renegade 1TB', 'base_price' => 1200000, 'tdp' => 8, 'performance_score' => 89, 'specs' => ['capacity' => '1TB', 'type' => 'NVMe SSD', 'interface' => 'M.2 PCIe 4.0 x4', 'read_speed' => '7300 MB/s', 'write_speed' => '6000 MB/s', 'form_factor' => 'M.2 2280'], 'compatibility_tags' => ['storage:nvme', 'storage:m2', 'pcie_gen:4']],

            // NVMe Gen 5
            ['name' => 'WD Black SN850X 1TB NVMe Gen5', 'brand' => 'Western Digital', 'model' => 'Black SN850X 1TB', 'base_price' => 1800000, 'tdp' => 10, 'performance_score' => 94, 'specs' => ['capacity' => '1TB', 'type' => 'NVMe SSD', 'interface' => 'M.2 PCIe 5.0 x4', 'read_speed' => '10000 MB/s', 'write_speed' => '9500 MB/s', 'form_factor' => 'M.2 2280'], 'compatibility_tags' => ['storage:nvme', 'storage:m2', 'pcie_gen:5']],
            ['name' => 'Corsair MP700 Pro 2TB NVMe Gen5', 'brand' => 'Corsair', 'model' => 'MP700 Pro 2TB', 'base_price' => 3500000, 'tdp' => 12, 'performance_score' => 96, 'specs' => ['capacity' => '2TB', 'type' => 'NVMe SSD', 'interface' => 'M.2 PCIe 5.0 x4', 'read_speed' => '12400 MB/s', 'write_speed' => '11800 MB/s', 'form_factor' => 'M.2 2280'], 'compatibility_tags' => ['storage:nvme', 'storage:m2', 'pcie_gen:5']],

            // SATA SSD
            ['name' => 'Samsung 870 EVO 1TB SATA SSD', 'brand' => 'Samsung', 'model' => '870 EVO 1TB', 'base_price' => 850000, 'tdp' => 4, 'performance_score' => 60, 'specs' => ['capacity' => '1TB', 'type' => 'SATA SSD', 'interface' => 'SATA III 6Gb/s', 'read_speed' => '560 MB/s', 'write_speed' => '530 MB/s', 'form_factor' => '2.5" / M.2'], 'compatibility_tags' => ['storage:sata', 'storage:ssd']],
            ['name' => 'Crucial MX500 1TB SATA SSD', 'brand' => 'Crucial', 'model' => 'MX500 1TB', 'base_price' => 750000, 'tdp' => 4, 'performance_score' => 58, 'specs' => ['capacity' => '1TB', 'type' => 'SATA SSD', 'interface' => 'SATA III 6Gb/s', 'read_speed' => '560 MB/s', 'write_speed' => '510 MB/s', 'form_factor' => '2.5"'], 'compatibility_tags' => ['storage:sata', 'storage:ssd']],

            // HDD
            ['name' => 'Seagate Barracuda 2TB HDD 7200RPM', 'brand' => 'Seagate', 'model' => 'Barracuda 2TB', 'base_price' => 650000, 'tdp' => 7, 'performance_score' => 35, 'specs' => ['capacity' => '2TB', 'type' => 'HDD', 'interface' => 'SATA III 6Gb/s', 'rpm' => '7200RPM', 'cache' => '256MB', 'form_factor' => '3.5"'], 'compatibility_tags' => ['storage:sata', 'storage:hdd']],
            ['name' => 'WD Blue 2TB HDD 7200RPM', 'brand' => 'Western Digital', 'model' => 'WD Blue 2TB', 'base_price' => 600000, 'tdp' => 7, 'performance_score' => 34, 'specs' => ['capacity' => '2TB', 'type' => 'HDD', 'interface' => 'SATA III 6Gb/s', 'rpm' => '7200RPM', 'cache' => '64MB', 'form_factor' => '3.5"'], 'compatibility_tags' => ['storage:sata', 'storage:hdd']],
        ];
        foreach ($storages as $item) {
            Component::create(['id' => Str::uuid(), 'category_id' => $storage->id, ...$item]);
        }

        // CPU COOLER
        $cooler = ComponentCategory::where('slug', 'cpu-cooler')->first();
        if ($cooler) {
            $coolers = [
                ['name' => 'Noctua NH-D15', 'brand' => 'Noctua', 'model' => 'NH-D15', 'base_price' => 1600000, 'tdp' => null, 'performance_score' => 98, 'specs' => ['type' => 'Air Cooler', 'socket_support' => ['AM4', 'AM5', 'LGA1700', 'LGA1851'], 'fan_size' => '2x 140mm', 'height' => '165mm', 'tdp_rating' => '250W'], 'compatibility_tags' => ['cooler:air', 'socket:AM4', 'socket:AM5', 'socket:LGA1700', 'socket:LGA1851']],
                ['name' => 'be quiet! Dark Rock 4', 'brand' => 'be quiet!', 'model' => 'Dark Rock 4', 'base_price' => 900000, 'tdp' => null, 'performance_score' => 90, 'specs' => ['type' => 'Air Cooler', 'socket_support' => ['AM4', 'AM5', 'LGA1700'], 'fan_size' => '1x 135mm', 'height' => '159mm', 'tdp_rating' => '200W'], 'compatibility_tags' => ['cooler:air', 'socket:AM4', 'socket:AM5', 'socket:LGA1700']],
                ['name' => 'DeepCool AK620', 'brand' => 'DeepCool', 'model' => 'AK620', 'base_price' => 750000, 'tdp' => null, 'performance_score' => 88, 'specs' => ['type' => 'Air Cooler', 'socket_support' => ['AM4', 'AM5', 'LGA1700', 'LGA1851'], 'fan_size' => '2x 120mm', 'height' => '160mm', 'tdp_rating' => '260W'], 'compatibility_tags' => ['cooler:air', 'socket:AM4', 'socket:AM5', 'socket:LGA1700', 'socket:LGA1851']],
                ['name' => 'Cooler Master Hyper 212 Black Edition', 'brand' => 'Cooler Master', 'model' => 'Hyper 212 Black Edition', 'base_price' => 350000, 'tdp' => null, 'performance_score' => 70, 'specs' => ['type' => 'Air Cooler', 'socket_support' => ['AM4', 'AM5', 'LGA1700'], 'fan_size' => '1x 120mm', 'height' => '158mm', 'tdp_rating' => '150W'], 'compatibility_tags' => ['cooler:air', 'socket:AM4', 'socket:AM5', 'socket:LGA1700']],
                ['name' => 'ARCTIC Liquid Freezer II 240', 'brand' => 'ARCTIC', 'model' => 'Liquid Freezer II 240', 'base_price' => 1100000, 'tdp' => null, 'performance_score' => 93, 'specs' => ['type' => 'AIO Liquid Cooler', 'socket_support' => ['AM4', 'AM5', 'LGA1700', 'LGA1851'], 'radiator_size' => '240mm', 'fan_size' => '2x 120mm', 'tdp_rating' => '300W'], 'compatibility_tags' => ['cooler:aio', 'socket:AM4', 'socket:AM5', 'socket:LGA1700', 'socket:LGA1851']],
                ['name' => 'Corsair iCUE H150i Elite LCD XT 360mm', 'brand' => 'Corsair', 'model' => 'iCUE H150i Elite LCD XT', 'base_price' => 2800000, 'tdp' => null, 'performance_score' => 97, 'specs' => ['type' => 'AIO Liquid Cooler', 'socket_support' => ['AM4', 'AM5', 'LGA1700', 'LGA1851'], 'radiator_size' => '360mm', 'fan_size' => '3x 120mm', 'tdp_rating' => '350W'], 'compatibility_tags' => ['cooler:aio', 'socket:AM4', 'socket:AM5', 'socket:LGA1700', 'socket:LGA1851']],
                ['name' => 'Lian Li Galahad 360 AIO', 'brand' => 'Lian Li', 'model' => 'Galahad 360', 'base_price' => 2200000, 'tdp' => null, 'performance_score' => 95, 'specs' => ['type' => 'AIO Liquid Cooler', 'socket_support' => ['AM4', 'AM5', 'LGA1700'], 'radiator_size' => '360mm', 'fan_size' => '3x 120mm', 'tdp_rating' => '350W'], 'compatibility_tags' => ['cooler:aio', 'socket:AM4', 'socket:AM5', 'socket:LGA1700']],
            ];
            foreach ($coolers as $item) {
                Component::create(['id' => Str::uuid(), 'category_id' => $cooler->id, ...$item]);
            }
        }

        // CASE
        $case = ComponentCategory::where('slug', 'case')->first();
        if ($case) {
            $cases = [
                ['name' => 'Lian Li Lancool 216', 'brand' => 'Lian Li', 'model' => 'Lancool 216', 'base_price' => 1200000, 'tdp' => null, 'performance_score' => 90, 'specs' => ['form_factor_support' => ['ATX', 'mATX', 'ITX'], 'max_gpu_length' => '420mm', 'max_cooler_height' => '176mm', 'drive_bays_35' => 2, 'drive_bays_25' => 4, 'radiator_support' => '360mm front'], 'compatibility_tags' => ['form_factor:ATX', 'form_factor:mATX', 'form_factor:ITX']],
                ['name' => 'Fractal Design Meshify C', 'brand' => 'Fractal Design', 'model' => 'Meshify C', 'base_price' => 1400000, 'tdp' => null, 'performance_score' => 88, 'specs' => ['form_factor_support' => ['ATX', 'mATX', 'ITX'], 'max_gpu_length' => '315mm', 'max_cooler_height' => '172mm', 'drive_bays_35' => 2, 'drive_bays_25' => 3, 'radiator_support' => '360mm front'], 'compatibility_tags' => ['form_factor:ATX', 'form_factor:mATX', 'form_factor:ITX']],
                ['name' => 'NZXT H510', 'brand' => 'NZXT', 'model' => 'H510', 'base_price' => 1100000, 'tdp' => null, 'performance_score' => 80, 'specs' => ['form_factor_support' => ['ATX', 'mATX', 'ITX'], 'max_gpu_length' => '381mm', 'max_cooler_height' => '165mm', 'drive_bays_35' => 2, 'drive_bays_25' => 2, 'radiator_support' => '240mm front'], 'compatibility_tags' => ['form_factor:ATX', 'form_factor:mATX', 'form_factor:ITX']],
                ['name' => 'Cooler Master NR200P', 'brand' => 'Cooler Master', 'model' => 'NR200P', 'base_price' => 900000, 'tdp' => null, 'performance_score' => 85, 'specs' => ['form_factor_support' => ['mATX', 'ITX'], 'max_gpu_length' => '330mm', 'max_cooler_height' => '153mm', 'drive_bays_35' => 2, 'drive_bays_25' => 2, 'radiator_support' => '240mm top'], 'compatibility_tags' => ['form_factor:mATX', 'form_factor:ITX']],
                ['name' => 'Phanteks Enthoo 719', 'brand' => 'Phanteks', 'model' => 'Enthoo 719', 'base_price' => 2200000, 'tdp' => null, 'performance_score' => 92, 'specs' => ['form_factor_support' => ['E-ATX', 'ATX', 'mATX', 'ITX'], 'max_gpu_length' => '500mm', 'max_cooler_height' => '185mm', 'drive_bays_35' => 6, 'drive_bays_25' => 6, 'radiator_support' => '480mm front'], 'compatibility_tags' => ['form_factor:E-ATX', 'form_factor:ATX', 'form_factor:mATX', 'form_factor:ITX']],
            ];
            foreach ($cases as $item) {
                Component::create(['id' => Str::uuid(), 'category_id' => $case->id, ...$item]);
            }
        }
    }
}